// Generated by gencpp from file musa/AddTwoInts.msg
// DO NOT EDIT!


#ifndef MUSA_MESSAGE_ADDTWOINTS_H
#define MUSA_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <musa/AddTwoIntsRequest.h>
#include <musa/AddTwoIntsResponse.h>


namespace musa
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace musa


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::musa::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::musa::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::musa::AddTwoInts > {
  static const char* value()
  {
    return "musa/AddTwoInts";
  }

  static const char* value(const ::musa::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::musa::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::musa::AddTwoInts >
template<>
struct MD5Sum< ::musa::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::musa::AddTwoInts >::value();
  }
  static const char* value(const ::musa::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::musa::AddTwoIntsRequest> should match
// service_traits::DataType< ::musa::AddTwoInts >
template<>
struct DataType< ::musa::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::musa::AddTwoInts >::value();
  }
  static const char* value(const ::musa::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::musa::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::musa::AddTwoInts >
template<>
struct MD5Sum< ::musa::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::musa::AddTwoInts >::value();
  }
  static const char* value(const ::musa::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::musa::AddTwoIntsResponse> should match
// service_traits::DataType< ::musa::AddTwoInts >
template<>
struct DataType< ::musa::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::musa::AddTwoInts >::value();
  }
  static const char* value(const ::musa::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MUSA_MESSAGE_ADDTWOINTS_H
