// Generated by gencpp from file musa/CounterGoal.msg
// DO NOT EDIT!


#ifndef MUSA_MESSAGE_COUNTERGOAL_H
#define MUSA_MESSAGE_COUNTERGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace musa
{
template <class ContainerAllocator>
struct CounterGoal_
{
  typedef CounterGoal_<ContainerAllocator> Type;

  CounterGoal_()
    : Limit(0)  {
    }
  CounterGoal_(const ContainerAllocator& _alloc)
    : Limit(0)  {
  (void)_alloc;
    }



   typedef int64_t _Limit_type;
  _Limit_type Limit;





  typedef boost::shared_ptr< ::musa::CounterGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::musa::CounterGoal_<ContainerAllocator> const> ConstPtr;

}; // struct CounterGoal_

typedef ::musa::CounterGoal_<std::allocator<void> > CounterGoal;

typedef boost::shared_ptr< ::musa::CounterGoal > CounterGoalPtr;
typedef boost::shared_ptr< ::musa::CounterGoal const> CounterGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::musa::CounterGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::musa::CounterGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::musa::CounterGoal_<ContainerAllocator1> & lhs, const ::musa::CounterGoal_<ContainerAllocator2> & rhs)
{
  return lhs.Limit == rhs.Limit;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::musa::CounterGoal_<ContainerAllocator1> & lhs, const ::musa::CounterGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace musa

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::musa::CounterGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::musa::CounterGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::musa::CounterGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::musa::CounterGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::musa::CounterGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::musa::CounterGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::musa::CounterGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f74e2cd829d807680604a2a671162f6d";
  }

  static const char* value(const ::musa::CounterGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf74e2cd829d80768ULL;
  static const uint64_t static_value2 = 0x0604a2a671162f6dULL;
};

template<class ContainerAllocator>
struct DataType< ::musa::CounterGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "musa/CounterGoal";
  }

  static const char* value(const ::musa::CounterGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::musa::CounterGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int64 Limit\n"
;
  }

  static const char* value(const ::musa::CounterGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::musa::CounterGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Limit);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CounterGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::musa::CounterGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::musa::CounterGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "Limit: ";
    Printer<int64_t>::stream(s, indent + "  ", v.Limit);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUSA_MESSAGE_COUNTERGOAL_H
